taskmanagementsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("task/", include("tasks.urls")),
    path("users/", include("users.urls")),
]

tasks/urls.py
from django.conf.urls import url, include
from django.urls import reverse
from tasks.views import TaskCreateView, TaskListView

app_name = "tasks"

urlpatterns = [
    url(r"^new/$", TaskCreateView.as_view(success_url="/task/list/"), name="new"),
    url(r"^list/$", TaskListView.as_view(), name="list"),
]

users/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    url(
        r"^login/$",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    url(
        r"^logout/$",
        auth_views.LogoutView.as_view(template_name="tasks/task_list.html"),
        name="logout",
    ),
    url(r"^signup/$", views.signup, name="signup"),
    url(r"^profile/$", views.profile, name="profile"),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    due_date = models.DateField("due date")

users/models.py
from django.db import models

# Create your models here.

tasks/forms.py
from django import forms

from tasks.models import Task


class TaskForm(forms.ModelForm):
    title = forms.CharField(max_length=30)
    description = forms.CharField(widget=forms.Textarea)
    due_date = forms.DateField(help_text="yyyy-mm-dd")

    class Meta:
        model = Task
        fields = ("title", "description", "due_date")

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(
        max_length=254, required=True, help_text="Enter a valid email address."
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

tasks/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from tasks.models import Task
from tasks.forms import TaskForm
from taskmanagementsite.settings import EMAIL_HOST_USER


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/task_create.html"
    fields = ["title", "description", "due_date"]
    login_url = "/users/login/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        send_mail(
            form.instance.title,
            form.instance.description + " " + str(form.instance.due_date),
            EMAIL_HOST_USER,
            [EMAIL_HOST_USER],
            fail_silently=False,
        )
        return super(TaskCreateView, self).form_valid(form)


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/task_list.html"
    context_object_name = "tasks"
    login_url = "/users/login/"

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)

users/views.py
from django.contrib.auth import login, authenticate, get_user
from django.shortcuts import render, redirect
from users.forms import SignUpForm
from taskmanagementsite.settings import LOGIN_REDIRECT_URL


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(LOGIN_REDIRECT_URL)
    else:
        form = SignUpForm()
    return render(request, "users/signup.html", {"form": form})


def profile(request):
    user = get_user(request)
    return render(request, "users/profile.html", {"user": user})

tasks/templates/tasks/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">TaskManagement</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav select-active">
                    <li><a href="{% url 'tasks:new' %}">Create Task</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'tasks:list' %}">Your Tasks</a></li>
                        <li><a href="{% url 'users:profile'%}">Your Profile</a></li>
                        <li><a href="{% url 'users:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                        <li><a href="{% url 'users:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container page-wrapper">
        {% block content %} {% endblock %}
    </div>

    <div class="footer">
        <p style=""></p>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

tasks/templates/tasks/task_create.html
{% extends 'tasks/base.html' %}

{% block title %}Create Task {% endblock %}

{% block content %}
<div class="col-md-offset-2 col-md-8">
    <h2>Create New Task</h2><hr>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <div class="form-group">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
  </form>
</div>
{% endblock %}

tasks/templates/tasks/task_list.html
{% extends 'tasks/base.html' %}

{% block title %}Tasks {% endblock %}

{% block content %}
<div class="col-md-offset-2 col-md-8">
    <h2>Tasks</h2><br>
    {% if tasks %}
        {% for task in tasks %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Title: {{ task.title }}</h5>
                    <p class="card-text">
                        Description: {{ task.description }} <br>
                        Due Date: {{ task.due_date}} <br>
                        Created by: {{ task.user.username }}<br>
                    </p>
                </div>
            </div>
            <br><br>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'tasks/base.html' %}
{% block title %}User Login{% endblock %}

{% block content %}
<div class="col-md-offset-3 col-md-5">
    <h2>Login to Your Account</h2><hr>
    <form method="post">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}

        <div class="form-group">
            <button type="submit" class="btn btn-success">Login</button>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'tasks/base.html' %}
{% block title %}User Profile{% endblock %}

{% block content %}
<div class="col-md-offset-3 col-md-5">
    <h2>Your profile</h2><hr>
    {% if user %}
        <p>User Email: {{ user.email }} </p>
        <p>First Name: {{ user.first_name }} </p>
        <p>Last Name: {{ user.last_name }} </p>
    {% endif %}
{% endblock %}

users/templates/users/signup.html
{% extends 'tasks/base.html' %}

{% block content %}

<div class="col-md-offset-3 col-md-5">
    <h2>Create Account</h2><hr>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <div class="form-group">
            <button type="submit" class="btn btn-success">Signup</button>
        </div>
    </form>
</div>

{% endblock %}